### PR TITLE
Force delete branch fix | New command: "Switch to remote branch"

### PR DESCRIPTION
**Pull request by Jagget**
Added two new commands that helped me to set up mobile client.

On mobile client:
* Create a temporary branch.
* Force-delete desynchronized branch
* Checkout remote branch

### CODE REVIEW

**Comment by Jagget** [comment]
@denolehov I would really appreciate it if you could look at this PR. It will help me to set up a mobile client properly.

**Comment by Vinzent03** [comment]
Hey thanks for your contribution! Sorry for taking so long for an answer.
Do you really need the force delete branch command? I check whether it can be deleted without force and asks again it needs force. Didn't work that or did you just want to add a quicker way?

**Comment by Jagget** [comment]
@Vinzent03 well, judging by the code, there should be a confirmation dialog, if the "force" parameter is needed. But I couldn't make it work, so I thought, maybe it's ok to add an option to set this parameter from the outside, without first asking Git to check it.

**Comment by Jagget** [comment]
Ok, I'll adjust the PR this way.

**Comment by Jagget** [comment]
@Vinzent03 updated the PR

**Comment by Vinzent03** [comment]
LGTM! Thanks for your contribution!

**Pull request merged**
