### PR TITLE
Mobile

### PR DESCRIPTION
**Pull request by Vinzent03**
# Checklist
- [x] commit
- [x] push
- [x] pull
- [x] status
- [x] error handling
- [x] validation check
- [x] Repository init
- [x] settings pane with configurations
- [x] disable status bar on mobile
- [x] port `simple-git` to new plugin structure
- [x] documentation
- [ ] community security check (I want to check the secure use of the personal access-token)

### CODE REVIEW

**Comment by hardenchant** [comment]
I want install plugin version on my phone from this branch for tests, how can i do this?
Build and replace files main.js and manifest.json at .obsidian folder on my android smartphone not working for me.

**Comment by Vinzent03** [comment]
@hardenchant You need to remove any node imports. So you have to delete the simple git file. Just ignore the import errors now. I think there is also a child process import in main.ts. this import needs to be deleted too. A bit tricky I know. The only import/require at the top of main.js should be obsidian.

**Comment by Ellpeck** [comment]
Is there anything we can do to help with this? I am looking forward to this being implemented; this plugin is awesome!!

**Comment by Vinzent03** [comment]
See merged #270

**Pull request closed without merging**
